routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [
    'uses' => 'BlogController@index',
    'as' => 'blog'
]);


Route::get('/blog/{post}',[
    'uses' => 'BlogController@show',
    'as' => 'blog.show'
]);

Route::post('/post/{post}/comments', [
    'uses' => 'CommentsController@store',
    'as' => 'blog.comments'
]);

Route::get('/category/{category}' , [
    'uses' => 'BlogController@category',
    'as' => 'category'
]);

Route::get('/author/{author}' , [
    'uses' => 'BlogController@author',
    'as' => 'author'
]);

Route::get('/tag/{tag}' , [
    'uses' => 'BlogController@tag',
    'as' => 'tag'
]);

Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

Auth::routes();

Route::get('/home', 'backend\HomeController@index')->name('home');
Route::get('/edit-account', 'Backend\HomeController@edit')->name('edit.account');
Route::put('/edit-account', 'Backend\HomeController@update')->name('edit.account');


Route::put('/backend/blog/restore/{blog}', [
    'uses' => 'Backend\BlogController@restore',
    'as' => 'backend.blog.restore'
]);
Route::delete('/backend/blog/force-destroy/{blog}', [
    'uses' => 'Backend\BlogController@forceDestroy',
    'as' => 'backend.blog.force-destroy'
]);
Route::resource('/backend/blog', 'Backend\BlogController', [
    'as'=>'backend'
]);

Route::resource('/backend/categories', 'Backend\CategoriesController', [
    'as'=>'backend'
]);

Route::get('/backend/users/confirm/{user}',[
    'uses' => 'Backend\UsersController@confirm',
    'as' => 'backend.users.confirm'
]);
Route::resource('/backend/users', 'Backend\UsersController', [
    'as'=>'backend'
]);

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;
use GrahamCampbell\Markdown\Facades\Markdown;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    use SoftDeletes;

    protected $fillable = ['title', 'slug', 'excerpt', 'body', 'published_at', 'category_id', 'image'];

    protected $dates = ['published_at'];

    public function author() {
        return $this->belongsTo(User::class);
    }

    public function category() {
        return $this->belongsTo(Category::class);
    }

    public function tags(){
        return $this->belongsToMany(Tag::class);
    }

    public function comments(){
        return $this->hasMany(Comment::class);
    }

    public function commentsNumber($label = "Comment") {
        $commentsNumber = $this->comments->count();
        
        return $commentsNumber." ". str_plural($label, $commentsNumber );
    }

    public function createComment(array $data){
        $this->comments()->create($data);
    }

    public function setPublishedAtAttribute($value){
        $this->attributes['published_at'] = $value ? : NULL;
    }

    public function getImageUrlAttribute($value) {

        $imageUrl = "";
        if(! is_null($this->image)){
            $directory = config('cms.image.directory');
            $imagePath=public_path() . "/{$directory}/" .$this->image;
            if(file_exists($imagePath)) $imageUrl = asset("{$directory}/" . $this->image);
        }

        return $imageUrl;
    }

    public function getImageThumbUrlAttribute($value) {

        $imageUrl = "";
        if(! is_null($this->image)){
            $directory = config('cms.image.directory');
            $ext = substr(strrchr($this->image, '.'),1);
            $thumbnail = str_replace(".{$ext}", "_thumb.{$ext}", $this->image);
            $imagePath=public_path() . "/{$directory}/" .$thumbnail;
            if(file_exists($imagePath)) $imageUrl = asset("{$directory}/" . $this->image);
        }

        return $imageUrl;
    }

    public function getDateAttribute($value) {
        return is_null($this->published_at) ? '' : $this->published_at->diffForHumans();
    }

    public function scopeLatestFirst($query){
        return $query->orderBy('created_at', 'desc');
    }

    public function scopePopular($query) {
        return $query->orderBy('view_count', 'desc');
    }

    public function scopePublished($query) {
        return $query->where("published_at", "<=", Carbon::now());
    }

    public function scopeScheduled($query) {
        return $query->where("published_at", ">", Carbon::now());
    }

    public function scopeDraft($query) {
        return $query->whereNull("published_at");
    }

    public static function archieve() {
        return static::selectRaw('count(id) as post_count, year(published_at) year, monthname(published_at) month')
            ->published()
            ->groupBy('year', 'month')
            ->orderByRaw('min(published_at) desc')
            ->get();
    }

    public function getBodyHtmlAttribute($value){
        return $this->body ? Markdown::convertToHtml(e($this->body)) : NULL;
    }

    public function dateFormatted($showTimes=false) {
        $format = "d/m/Y";
        if($showTimes) $format = $format." H:i:s";
        return $this->created_at->format($format);
    }

    public function publicationLabel(){
        if(! $this->published_at) {
            return '<span class="label label-warning">Daft</span>';
        } elseif ($this->published_at && $this->published_at->isFuture()) {
            return '<span class="label label-info">Schedule</span>';
        } else {
            return '<span class="label label-success">Published</span>';
        }
    }

    public function getExcerptHtmlAttribute($value){
        return $this->body ? Markdown::convertToHtml(e($this->excerpt)) : NULL;
    }

    public function getTagsHtmlAttribute(){
        $anchors = [];
        foreach ($this->tags as $tag) {
            $anchors[] = "<a href=\"".route('tag', $tag->slug)."\">". $tag->name ."</a>";
        }
        return implode(", ",$anchors);
    }

    public function getRouteKeyName()
    {
        return "slug";
    }

    public function scopeFilter($query, $filter){

        if(isset($filter['month']) && $month = $filter['month']) {
            $query->whereMonth('published_at', Carbon::parse($month)->month);
        }

        if(isset($filter['year']) && $year = $filter['year']) {
            $query->whereYear('published_at', $year);
        }

        if(isset($filter['term']) && $term = $filter['term']){
            $query->where(function($q) use ($term) {
                // $q->whereHas('author', function($qr) use ($term) {
                //     $qr->where('name', 'LIKE', "%{$term}%");
                // });
                // $q->whereHas('category', function($qr) use ($term) {
                //     $qr->where('title', 'LIKE', "%{$term}%");
                // });
                $q->orWhere('title', 'LIKE', "%{$term}%");
                $q->orWhere('excerpt', 'LIKE', "%{$term}%");
            });
        }
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use GrahamCampbell\Markdown\Facades\Markdown;
use Laratrust\Traits\LaratrustUserTrait;

class User extends Authenticatable
{
    use Notifiable;
    use LaratrustUserTrait;

    protected $fillable = [
        'name', 'email', 'password', 'slug', 'bio'
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function posts(){
        return $this->hasMany(Post::class, 'author_id');
    }

    public function gravatar() {
        $email = $this->email;
        // $default = asset("img/author.jpg");
        $default = "https://www.gravatar.com/avatar/?d=identicon";
        $size = 100;

        return "https://www.gravatar.com/avatar/" . md5( strtolower( trim( $email ) ) ) . "?d=" . urlencode( $default ) . "&s=" . $size;
    }

    public function getBioHtmlAttribute($value){
        return $this->bio ? Markdown::convertToHtml(e($this->bio)) : NULL;
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function setPasswordAttribute($value)
    {
        if (!empty($value)) $this->attributes['password'] = bcrypt($value);
    }
}

app/Http/Controllers/Backend/BlogController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Post;
use Intervention\Image\Facades\Image;

class BlogController extends BackendController
{
    protected $uploadPath;


    public function __construct()
    {
        parent::__construct();
        $this->uploadPath = public_path(config('cms.image.directory'));
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        $onlyTrashed = FALSE;

        if(($status = $request->get('status')) && $status == 'trash' ) {
            $posts = Post::onlyTrashed()->with('category', 'author')->latest()->paginate($this->limit);
            $postCount = Post::onlyTrashed()->count();

            $onlyTrashed = TRUE;
        } elseif($status=='published') {

            $posts = Post::published()->with('category', 'author')->latest()->paginate($this->limit);
            $postCount = Post::published()->count();

        } elseif($status=='scheduled') {

            $posts = Post::scheduled()->with('category', 'author')->latest()->paginate($this->limit);
            $postCount = Post::scheduled()->count();

        } elseif($status=='draft') {

            $posts = Post::draft()->with('category', 'author')->latest()->paginate($this->limit);
            $postCount = Post::draft()->count();

        } elseif($status=='own') {

            $posts = $request->user()->posts()->with('category', 'author')->latest()->paginate($this->limit);
            $postCount = $request->user()->posts()->count();

        } else {

            $posts = Post::with('category', 'author')->latest()->paginate($this->limit);
            $postCount = Post::count();

        }

        $statusList = $this->statusList($request);

        return view("backend.blog.index", compact('posts', 'postCount', 'onlyTrashed', 'statusList'));
    }

    private function statusList($request){
        return [
            'own' => $request->user()->posts()->count(),
            'all' => Post::count(),
            'published' => Post::published()->count(),
            'scheduled' => Post::scheduled()->count(),
            'draft' => Post::draft()->count(),
            'trash' => Post::onlyTrashed()->count(),

        ];
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Post $post)
    {
        return view("backend.blog.create", compact('post'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Requests\PostRequest $request)
    {
        $data = $this->handleRequest($request);
        $request->user()->posts()->create($data);

        return redirect(route('backend.blog.index'))->with('message', 'Your posts was created successfully');
    }

    private function handleRequest($request) {
        $data = $request->all();

        if($request->hasFile('image')){
            $image = $request->file('image');
            $fileName = $image->getClientOriginalName();
            $destination = $this->uploadPath;

            $successUploaded = $image->move($destination, $fileName);

            if($successUploaded){
                $width = config('cms.image.thumbnail.width');
                $height = config('cms.image.thumbnail.height');
                $extension = $image->getClientOriginalExtension();
                $thumbnail = str_replace(".{$extension}", "_thumb.{$extension}", $fileName);

                Image::make($destination . '/' . $fileName)->resize($width, $height)->save($destination . '/'. $thumbnail);
            }

            $data['image']=$fileName;
        }

        return $data;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::findOrFail($id);
        return view('backend.blog.edit', compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Requests\PostRequest $request, $id)
    {
        $post = Post::findOrFail($id);

        $oldImage = $post->image;

        $data = $this->handleRequest($request);
        $post->update($data);

        if($oldImage !== $post->image){
            $this->removeImage($oldImage);
        }

        return redirect(route('backend.blog.index'))->with('message', 'Your posts was updated successfully');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Post::findOrFail($id)->delete();

        return redirect(route('backend.blog.index'))->with('trash-message', ['Your posts was moved to Trash', $id]);

    }

    public function forceDestroy($id){
        $post = Post::onlyTrashed()->findOrFail($id);
        $post->forceDelete();

        $this->removeImage($post->image);

        return redirect('/backend/blog?status=trash')->with('message', 'Your posts has been deleted succesfully');
    }

    public function restore($id) {
        $post = Post::withTrashed()->findOrFail($id);
        $post->restore();

        return redirect()->back()->with('message', 'Your posts has been moved from the Trash');

    }

    private function removeImage($image){
        if(! empty($image)){
            $imagePath = $this->uploadPath .'/'. $image;
            $ext = substr(strrchr($image, '.'), 1);
            $thumbnail = str_replace(".{$ext}", "_thumb.{$ext}", $image);
            $thumbnailPath = $this->uploadPath .'/'. $thumbnail;

            if(file_exists($imagePath)) unlink($imagePath);
            if(file_exists($thumbnailPath)) unlink($thumbnailPath);

        }
    }
    
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Post;
use App\Category;
use App\User;
use App\Tag;

class BlogController extends Controller
{

    protected $limit = 5;
    
    public function index(){

        $posts = Post::with('author', 'tags', 'category', 'comments')
        ->latestFirst()
        ->published()
        ->filter(request()->only(['term', 'year', 'month']))
        ->simplePaginate($this->limit);        

        return view('blog.index', compact('posts'));  
    }

    public function category(Category $category){

        $categoryName = $category->title;

        $posts = $category->posts()
            ->with('author', 'tags', 'comments')
            ->latestFirst()
            ->published()
            ->simplePaginate($this->limit);

        return view('blog.index', compact('posts', 'categoryName'));

    }

    public function tag(Tag $tag){

        $tagName = $tag->title;

        $posts = $tag->posts()
            ->with('author', 'category', 'comments')
            ->latestFirst()
            ->published()
            ->simplePaginate($this->limit);

        return view('blog.index', compact('posts', 'categoryName'));

    }

    public function author(User $author){

        $authorName = $author->name;

        $posts = $author->posts()
            ->with('category', 'tags', 'comments')
            ->latestFirst()
            ->published()
            ->simplePaginate($this->limit);

        return view('blog.index', compact('posts', 'authorName'));

    }

    public function show(Post $post) {



        //update posts set view_count = view_count + 1 Where id = ?
        # 1
        // $viewCount = $post->view_count + 1;
        // $post->update(['view_count'=> $viewCount]);

        # 2
        $post->increment('view_count');

        $postComments = $post->comments()->simplePaginate(3);

        return view("blog.show", compact('post', 'postComments'));
    }
 
    
}

resources/views/blog/alert.blade.php
@if (isset($categoryName)) 

    <div class="alert alert-info">
        <p>Category: <strong>{{ $categoryName }}</strong></p>
    </div>
    
@endif

@if (isset($tagName)) 

    <div class="alert alert-info">
        <p>Tag: <strong>{{ $tagName }}</strong></p>
    </div>
    
@endif

@if (isset($authorName)) 

    <div class="alert alert-info">
        <p>Author: <strong>{{ $authorName }}</strong></p>
    </div>
    
@endif

@if ($term = request('term')) 

    <div class="alert alert-info">
        <p>Search Results for: <strong>{{ $term }}</strong></p>
    </div>
    
@endif

resources/views/blog/comments.blade.php
<article class="post-comments" id="post-comments">    
<h3><i class="fa fa-comments"></i>{{ $post->commentsNumber('Comment') }}</h3>

        <div class="comment-body padding-10">
            <ul class="comments-list">
                @foreach ($postComments as $comment)
                    <li class="comment-item">
                        <div class="comment-heading clearfix">
                            <div class="comment-author-meta">
                            <h4>{{$comment->author_name}}<small>{{ $comment->date }}</small></h4>
                            </div>
                        </div>
                        <div class="comment-content">
                            {!! $comment->body_html !!}
                        </div>
                    </li>
                    
                @endforeach             

            </ul>

            <nav>
                {!! $postComments->links() !!}
            </nav>

        </div>

        <div class="comment-footer padding-10">
            <h3>Leave a comment</h3>

            @if (session('message'))
                <div class="alert alert-info">{{ session('message') }}</div>
            @endif

            {!! Form::open(['route'=> ['blog.comments', $post->slug]]) !!}
                <div class="form-group required {{ $errors->has('author_name') ? 'has-error' : '' }}">
                    <label for="name">Name</label>
                    {!! Form::text('author_name', null, ['class'=>'form-control']) !!}
                    @if ($errors->has('author_name'))
                        <span class="have-block"><strong>{{$errors->first('author_name')}}</strong></span>                        
                    @endif
                </div>
                <div class="form-group required {{ $errors->has('author_email') ? 'has-error' : '' }}">
                    <label for="email">Email</label>
                    {!! Form::text('author_email', null, ['class'=>'form-control']) !!}
                    @if ($errors->has('author_email'))
                        <span class="have-block"><strong>{{$errors->first('author_email')}}</strong></span>                        
                    @endif
                </div>
                <div class="form-group">
                    <label for="website">Website</label>
                    {!! Form::text('author_url', null, ['class'=>'form-control']) !!}
                </div>
                <div class="form-group required {{ $errors->has('body') ? 'has-error' : '' }}">
                    <label for="comment">Comment</label>
                    {!! Form::textarea('body', null, ['row'=>6,'class'=>'form-control']) !!}
                    @if ($errors->has('body'))
                        <span class="have-block"><strong>{{$errors->first('body')}}</strong></span>                        
                    @endif

                </div>
                <div class="clearfix">
                    <div class="pull-left">
                        <button type="submit" class="btn btn-lg btn-success">Submit</button>
                    </div>
                    <div class="pull-right">
                        <p class="text-muted">
                            <span class="required">*</span>
                            <em>Indicates required fields</em>
                        </p>
                    </div>
                </div>
            {!! Form::close() !!}
        </div>

    </article>

resources/views/blog/index.blade.php
@extends('layouts.main')

@section('content')

<div class="container">
    <div class="row">
        <div class="col-md-8">

            @if (!$posts->count())
                <div class="alert alert-warning">
                    <p>Nothing Found</p>
                </div>
            @else

                @include('blog.alert')

                @foreach ($posts as $post)
                
                    <article class="post-item">
                        
                        @if ($post->imageurl)
                            <div class="post-item-image">
                                <a href="{{ route('blog.show', $post->slug ) }}">
                                    <img src="{{ $post->image_url }} " alt="">
                                </a>
                            </div>
                        @endif
                            
                        <div class="post-item-body">
                            <div class="padding-10">
                                <h2><a href="{{ route('blog.show', $post->slug ) }}">{{ $post->title }}</a></h2>
                                {!! $post->excerpt_html !!}
                            </div>
        
                            <div class="post-meta padding-10 clearfix">
                                <div class="pull-left">
                                    <ul class="post-meta-group">
                                        <li><i class="fa fa-user"></i><a href="{{ route('author', $post->author->slug) }}"> {{ $post->author->name }}</a></li>
                                        <li><i class="fa fa-clock-o"></i><time> {{ $post->date }}</time></li>
                                        <li><i class="fa fa-folder"></i><a href="{{ route('category', $post->category->slug) }}"> {{ $post->category->title }}</a></li>
                                        <li><i class="fa fa-tag"></i>{!! $post->tags_html !!}</li>
                                    <li><i class="fa fa-comments"></i><a href="{{ route('blog.show', $post->slug ) }}#post-comments">{{ $post->commentsNumber('Comment') }}</a></li>
                                    </ul>
                                </div>
                                <div class="pull-right">
                                    <a href="{{ route('blog.show', $post->slug ) }}">Continue Reading &raquo;</a>
                                </div>
                            </div>
                        </div>
                    </article>

                @endforeach
            @endif

            <nav>
              {{ $posts->appends(request()->only(['term', 'month', 'year']))->links() }}
            </nav>
        </div>
        
        @include('layouts.sidebar')

    </div>
</div>

@endsection

resources/views/blog/show.blade.php
@extends('layouts.main')

@section('content')

<div class="container">
    <div class="row">
        <div class="col-md-8">
                <article class="post-item post-detail">
                    @if ($post->image_url)
                        <div class="post-item-image">
                            {{-- <a href="#"> --}}
                                <img src="{{ $post->image_url }}" alt="">
                            {{-- </a> --}}
                        </div>
                    @endif
    
                        <div class="post-item-body">
                            <div class="padding-10">
                                <h1>{{ $post->title }}</h1>
    
                                <div class="post-meta no-border">
                                    <ul class="post-meta-group">
                                    <li><i class="fa fa-user"></i><a href="{{ route('author', $post->author->slug) }}"> {{ $post->author->name }}</a></li>
                                        <li><i class="fa fa-clock-o"></i><time> {{ $post->date }}</time></li>
                                        <li><i class="fa fa-folder"></i><a href="{{ route('category', $post->category->slug) }}"> {{ $post->category->title }}</a></li>
                                        <li><i class="fa fa-tag"></i> {!! $post->tags_html !!}</a></li>
                                    <li><i class="fa fa-comments"></i><a href="#post-comments">{{ $post->commentsNumber('Comment') }}</a></li>
                                    </ul>
                                </div>
    
                               {!! $post->body_html !!}
                            </div>
                        </div>
                    </article>
    
                    <article class="post-author padding-10">
                        <div class="media">
                          <div class="media-left">
                              <?php $author = $post->author; ?>
                            <a href="{{ route('author', $author->slug ) }}">
                              <img alt={{ $author->name }} src="{{ $author->gravatar() }}" class="media-object">
                            </a>
                          </div>
                          <div class="media-body">
                            <h4 class="media-heading"><a href="{{ route('author', $author->slug) }}">{{ $author->name }}</a></h4>
                            <div class="post-author-count">
                              <a href="{{ route('author', $author->slug) }}">
                                  <i class="fa fa-clone"></i>
                                  <?php $postCount = $author->posts()->published()->count() ?>
                                  {{ $postCount }} {{ str_plural('post', $postCount) }}
                              </a>
                            </div>
                            {!! $author->bio_html !!}
                          </div>
                        </div>
                    </article>
                    
                    @include('blog.comments')
                    
                
        </div>
        
        @include('layouts.sidebar')

    </div>
</div>

@endsection